name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [labeled, opened, synchronize]

jobs:
  automerge:
    if: |
      github.actor == 'dependabot[bot]' && 
      github.event.pull_request.mergeable_state == 'clean'
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
