name: Go Backend Tests

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/go-test.yml'
    branches: [ main ]
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/go-test.yml'
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'backend/go.mod'

    - name: Install dependencies
      run: cd backend && go mod download

    - name: Run tests
      run: cd backend && go test ./... -v -cover

    - name: Generate coverage report
      run: |
        cd backend
        go test ./... -coverprofile=coverage.out
        go tool cover -func=coverage.out
        mkdir -p coverage-report
        go tool cover -html=coverage.out -o coverage-report/index.html

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: backend/coverage-report/
        retention-days: 7

